CREATE TABLE patients (
	id INTEGER NOT NULL, 
	mrn VARCHAR(50), 
	name VARCHAR, 
	age INTEGER, 
	gender VARCHAR, 
	contact VARCHAR, 
	created_at DATETIME, email TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (mrn)
);\n\nCREATE TABLE doctors (
	id INTEGER NOT NULL, 
	name VARCHAR NOT NULL, 
	email VARCHAR NOT NULL, 
	specialization VARCHAR, 
	phone VARCHAR, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (email)
);\n\nCREATE TABLE users (
	id INTEGER NOT NULL, 
	username VARCHAR NOT NULL, 
	email VARCHAR NOT NULL, 
	password_hash VARCHAR NOT NULL, 
	role VARCHAR, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	last_login DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (username), 
	UNIQUE (email)
);\n\nCREATE TABLE reports (
	id INTEGER NOT NULL, 
	patient_id INTEGER, 
	filename VARCHAR, 
	file_path TEXT, 
	uploaded_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id)
);\n\nCREATE TABLE predictions (
	id INTEGER NOT NULL, 
	patient_id INTEGER, 
	risk_level VARCHAR, 
	confidence FLOAT, 
	probabilities TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id)
);\n\nCREATE TABLE appointments (
	id INTEGER NOT NULL, 
	patient_id INTEGER, 
	doctor_id INTEGER, 
	appointment_date DATETIME NOT NULL, 
	reason TEXT, 
	status VARCHAR, 
	priority INTEGER, 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id), 
	FOREIGN KEY(doctor_id) REFERENCES doctors (id)
);\n\nCREATE TABLE post_diagnosis (
	id INTEGER NOT NULL, 
	patient_id INTEGER NOT NULL, 
	diagnosis_date DATETIME NOT NULL, 
	cancer_type VARCHAR(100), 
	stage VARCHAR(20), 
	tumor_size_mm FLOAT, 
	lymph_nodes_affected INTEGER, 
	metastasis_status VARCHAR(50), 
	treatment_plan TEXT, 
	notes TEXT, 
	created_at DATETIME, 
	updated_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id)
);\n\nCREATE TABLE medical_images (
	id INTEGER NOT NULL, 
	patient_id INTEGER NOT NULL, 
	post_diagnosis_id INTEGER, 
	image_type VARCHAR(50), 
	file_path VARCHAR(500) NOT NULL, 
	upload_date DATETIME, 
	ai_analyzed BOOLEAN, 
	tumor_detected BOOLEAN, 
	confidence_score FLOAT, 
	tumor_count INTEGER, 
	largest_tumor_size FLOAT, 
	analysis_summary TEXT, 
	image_width INTEGER, 
	image_height INTEGER, 
	file_size_kb INTEGER, 
	notes TEXT, tumor_size_mm2 REAL, tumor_position_x REAL, tumor_position_y REAL, tumor_position_desc VARCHAR(50), tumor_mass_g REAL, aggression_level INTEGER, aggression_description VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id), 
	FOREIGN KEY(post_diagnosis_id) REFERENCES post_diagnosis (id)
);\n\nCREATE TABLE tumor_markers (
	id INTEGER NOT NULL, 
	patient_id INTEGER NOT NULL, 
	post_diagnosis_id INTEGER, 
	marker_name VARCHAR(50) NOT NULL, 
	value FLOAT NOT NULL, 
	unit VARCHAR(20), 
	test_date DATETIME NOT NULL, 
	reference_min FLOAT, 
	reference_max FLOAT, 
	is_abnormal BOOLEAN, 
	lab_name VARCHAR(200), 
	test_method VARCHAR(100), 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(patient_id) REFERENCES patients (id), 
	FOREIGN KEY(post_diagnosis_id) REFERENCES post_diagnosis (id)
);\n\n